### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by simonpulawski** [roborescue/rcrs-adf#12]
404 site not found error on the following urls containing documentation for roborescue/adf-core-java & /adf-sample-agent-java:
https://roborescue.github.io/rcrs-adf-sample/index.html
https://roborescue.github.io/rcrs-adf-sample/adf-manual.pdf
https://roborescue.github.io/rcrs-adf-sample/

**Comment by gnardin** [comment]
Please see [issue #20](https://github.com/roborescue/adf-sample-agent-java/issues/20) in the `adf-sample-agent-java` repository.
