### ISSUE TITLE
New Message Handler module

### ISSUE THREAD

**Issue by gnardin** [roborescue/rcrs-adf#2]
Implement a new Message Handler module in which teams may be able to select channels to listen or messages to receive.

**Comment by nobuhiro-ito** [comment]
This is a just comment.
When we improve ADF's modules, I'd like you to keep modularity of ADF.
This is an important step of us
Could you think about this improvement carefully.
Please, go ahead.

**Comment by modaresimr** [comment]
Also, this module or another module should be responsible for selecting
messages.
as an example, if we have 10 messages to send and we have only 20bytes,
which messages should be chosen?
or we have some worldmodel messages, they can be select and add to queue.

I think the message handler module can be separated to 3 module:
1- Responsible for selecting channels
2- Responsible for selecting messages
3- Responsible for adding global messages



2017-12-15 4:56 GMT+03:30 Nobuhiro Ito <notifications@github.com>:
