### ISSUE TITLE
Message manager does not return the messages from base class type

### ISSUE THREAD

**Issue by okanasik** [roborescue/rcrs-adf#7]
[MesssageManager](https://github.com/roborescue/rcrs-adf-core/blob/master/src/main/java/adf/agent/communication/MessageManager.java) when we call `messageManager.getReceivedMessageList(StandardMessage.class)` as in [MessageTool](https://github.com/roborescue/rcrs-adf-sample/blob/master/src/adf/sample/tactics/utils/MessageTool.java) `getReceivedMessageList` returns empty list since the method checks for class equality. Therefore, there is no message whose type is directly `StandardMessage`. Maybe this problem is solved by the teams using some workarounds such as getting particular messages and reflecting the changes on the world model, but this is very important bug for new teams. I am working on fix and will send when it is ready.

**Comment by tkmnet** [comment]
Thank you for improving the non user friendly method.
